name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test_app:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Build the app
        run: npm run build
      - name: e2e tests with cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          record: true
          wait-on: http://localhost:5173
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Upload Cypress Screenhots Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Screenhots
          path: cypress/screenshots

  trigger_deployment:
    # Trigger deployment only on push on main, and also when #skip is not present in commit message
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    needs: [build_and_test_app]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_SECRET_KEY }}

      - name: Notify about successful deployment
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          color: "#22BB33"
          text: A new version of Weather App deployed by ${{ github.event.head_commit.author.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Notify about unsuccessful deployment
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          text: Build failed for Weather App
          color: "#BB2124"
          details: https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.event.head_commit.author.username }} broke the build :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [trigger_deployment]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        with:
          fetch-depth: "0"
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          VERBOSE: true
          DEFAULT_BUMP: patch
